name: Artifact Purger

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge artifacts older than 1 hour
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 1 hour
